### ISSUE TITLE
Call to __open_missing_mode declared with attribute error

### ISSUE THREAD

**Issue by IAM-marco** [dj95/fn-notify#1]
Hey! I'm trying to compile this volume notifier, but after running `make all`, I immediately get:

    In file included from /usr/include/fcntl.h:289:0,
                     from fn-notify.c:17:
    In function ‘open’,
        inlined from ‘CheckForAnotherInstance’ at fn-notify.c:145:8:
    /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
        __open_missing_mode ();

Any suggestion?

**Comment by dj95** [comment]
Seems like I missed the file permissions there :D strange that gcc doesn't throw this error for me.  Can you try it again with the latest commit? It should be fixed now.

**Comment by IAM-marco** [comment]
It compiled successfully, but running `./fn-notify 34` returns `No arguments provided`

**Comment by dj95** [comment]
Nevermind... I forgot to update the readme. It's `./fn-notify vol 34` for volume and `./fn-notify brig 34` for brightness. Sorry

**Comment by IAM-marco** [comment]
Allright, it works.

Only thing is, once the notification is displayed and the app quits, it prints "No such file or directory"

**Comment by dj95** [comment]
Did you modify the path in the script? Check out the last commit and set the paths to your home-directory. Then it should work :)

**Comment by IAM-marco** [comment]
Which script are we talking about? I move the compiled bin to `/usr/bin/notifier` and just calling it.

The app works, it just returns that message

**Comment by dj95** [comment]
There are some issues with the lock file because I hardcoded paths into it. Let me check this after work.

**Comment by dj95** [comment]
Nevermind, I think I fixed it :D can you test with the latest commit, please?

**Comment by IAM-marco** [comment]
Works!
